[build-system]
requires = ["setuptools>=61.0", "whell"]
build-backend = "setuptools.build_meta"
[project]
name = "neurolixir"
version = "0.1.0"
dependencies = [
    "openai>=1.107.0",
    "pyttsx3>=2.99"
]